# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: Tallant 
email: your-email@domain.com
author: Nick Tallant 
description: > # "Write an awesome description for your new site here. 
    Applied Data & Governance Fellow, International Innovation Corps. MS-CAPP Candidate, University of Chicago
copyright: 'Copyright &copy; 2018 Nick Tallant. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source <a href="http://startbootstrap.com/">Bootstrap</a> theme.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/the_tallant
  - title: github
    url: https://github.com/ndtallant
  - title: linkedin
    url: https://www.linkedin.com/in/ndtallant/    
